### ISSUE TITLE
Take a look at my optimizer.

### ISSUE THREAD

**Issue by PusPC** [Idkjjjj/Idkjjjj.github.io#1]
Hello! Im the owner of the project called: PusPC its multiple tools but the best in it is: Windows 10 (Windows 11 under testing) debloater and speedup tool. I ask you to mention my program please. Because iam working hard on it to make it very good. So take a look at: https://puspc.site/ (Website)
https://github.com/puspc/pus
I would be happy if you mentioned my program in your guide to speed up computers.

**Comment by Idkjjjj** [comment]
Sure will try and review!
